### ISSUE TITLE
 Para os interessados neste Mini-Projecto

### ISSUE THREAD

**Issue by ishouldbedany** [dssg-pt/mp-violencia-domestica#1]
Se estás interessado em contribuir para este Mini-Projecto, deixa um comentário abaixo com o teu verso de poesia/música favorito! :point_down: 

:exclamation: A qualidade do verso será utilizada para seriar os interessados. Estamos a brincar, será à base de _first come, first served_. Mas agora que já têm o verso na mente e têm...

**Comment by joao-nunes** [comment]
Still open?
 
"We've got to build this world together/ Or we'll have no more future at all/ Because time/ It waits for nobody." (kinda clichê and unoriginal, but who cares? 🤷‍♂️)

**Comment by ishouldbedany** [comment]
Hi @joao-nunes! Sure. Just waiting for 1-2 other people to show interest and then we will be in touch.

**Comment by tiagovportela** [comment]
Open?
'Strangers passing in the street
By chance two separate glances meet
And I am you and what I see is me
And do I take you by the hand
And lead you through the land
And help me understand the best I can"

**Comment by RuiMedon** [comment]
Interested! 
"I loved your face, I loved your hair
Your T-shirts and your evening wear
As for the world, the job, the war
I ditched them all to love you more"

**Comment by sv-bazh** [comment]
Hello! Interested to participate! With which tool do you want the dashboard?

**Comment by vitorhcsousa** [comment]
Hi, I would like to help!

**Comment by oyidiyaoji** [comment]
Hi! I'm also interested. I would be glad to help!

**Comment by CatarinaNSSilva** [comment]
Hi, I'm happy to help!

**Comment by miguelduarte18** [comment]
Hey, estou disponível para ajudar. Tenho alguma experiência na entrega de projetos de BI.
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
🙂

**Comment by basketa** [comment]
Happy to help too.

**Comment by jbricenot** [comment]
Ola, quisera ajudar. Ja tenho experiencia com voces, fiz parte do mini-projecto "dados sobre o impacto de mercado de trabalho".

**Comment by tiago-sousa** [comment]
Hi! 
Probably you have more volunteers than you need, but I’m happy to help as well. In this or any other project.

**Comment by tiagofurtado** [comment]
Also available to help!

**Comment by joana9r** [comment]
Happy to help! :)

**Comment by barbara-abreu** [comment]
In case you need an extra hand :D , I would be happy to help.

**Comment by ishouldbedany** [comment]
Hi everyone and thanks a lot for the interest, we are always honoured by everyone's enthusiasm :blush: . 

As we said, we are going to follow a _first come, first served_ scheme for this recruitment, which means @joao-nunes, @tiagovportela and @RuiMedon. Can you three e-mail me at daniel@dssg.pt so we can set up the kick-off meeting?

@sv-bazh @VitorSousa5 @oyidiyaoji @CatarinaNSSilva @miguelduarte18 @basketa @jbricenot @tiago-sousa @tiagofurtado @joana9r @barbara-abreu Thanks a lot! We have more mini-projects in the pipeline, as well as a new full-blown Project (where recruitment is interview-based) coming out really soon. Stay tuned to our newsletter/social networks. 

Closing this one for now.
